x-defaults: &defaults
  restart: always

services:

  # this caddy uses DNS challenges, not requiring public port 443 access
  #  ie, you can run your service on a upnp-able port like 9443
  #   in case you have limited access, see router-config.js merely_upnp()
  caddy:
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:2-builder AS builder
        RUN xcaddy build --with github.com/caddy-dns/duckdns

        FROM caddy:2
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    environment:
      - DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    networks:
      - web
    <<: *defaults
    
  # See also theproxy/README.md to run the public Caddy server elsewhere.
  ssh-tunnel-source:
      build:
        context: .
        dockerfile_inline: |
          FROM alpine:3.19
          RUN apk add --no-cache openssh-client
          RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
      
      # the -R connects all their :3000 to the app server here
      command: |
        sh -c 'echo "$$SSH_PRIVATE_KEY" > /root/.ssh/id_ed25519 && \
        chmod 600 /root/.ssh/id_ed25519 && \
        exec ssh -v -N \
          -R 0.0.0.0:3000:app:3000 \
          -i /root/.ssh/id_ed25519 \
          -o ServerAliveInterval=30 \
          -o ExitOnForwardFailure=yes \
          -o StrictHostKeyChecking=accept-new \
          -p 2023 \
          root@d'
      environment:
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      depends_on:
        - app
      networks:
        - web
      <<: *defaults
    
  # the bun+vite+svelte+jamola app itself!
  app:
    build:
      context: .
      dockerfile_inline: |
        FROM oven/bun:1
        WORKDIR /app
        COPY package*.json ./
        RUN bun install
    volumes:
      # z lets SELinux share this mount (on Fedora, Debians have AppArmor which isn't fussy here)
      - .:/app:z
      # a more robust place for uploads/ perhaps?
      # if you want to serve this without the /error/ directory
      #  see https://github.com/sveltejs/kit/discussions/10162
      - /media/s/www:/app/static/error:ro
      # Prevent the container's node_modules from being overwritten by the host
      #  this means any `npm i ...` you make in another environ (eg the host)
      #   will need pushing to the container via package.json, the above RUN npm ci
        #  as part of a $ docker compose up --build
      - /app/node_modules
      - /app/.svelte-kit
    ports:
      - "127.0.0.1:9090:3000"
    command: bun run dev -- --port 3000 --host 0.0.0.0
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "http://127.0.0.1:9090"]
    #   interval: 2s
    #   timeout: 5s
    #   retries: 16
    #   start_period: 30s
    networks:
      - web
    <<: *defaults

volumes:
  caddy_data:
  caddy_config:

networks:
  web:

configs:
  caddy_config:
    content: |
      voulais-dev.duckdns.org {
          # Enable automatic HTTPS
          tls {
              dns duckdns $DUCKDNS_TOKEN
          }
          
          # Enable compression
          encode zstd gzip
          
          # Handle all requests
          handle {
              reverse_proxy app:3000
          }
          
          # Basic security headers
          header {
              # Enable HSTS
              Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
              # Prevent browsers from sniffing MIME types
              X-Content-Type-Options "nosniff"
              # XSS protection
              X-XSS-Protection "1; mode=block"
              # Click-jacking protection
              X-Frame-Options "DENY"
          }
          
          # Enable logging
          log {
              output file /var/log/caddy/access.log
              format console
          }
      }
      http://voulais.duckdns.org {
          redir https://{host}{uri} permanent
      }