
services:
  # the bun+vite+svelte+jamola app itself!
  app:
    build:
      context: .
      dockerfile_inline: |
        FROM alpine:3.19
        WORKDIR /app
        RUN apk add --no-cache \
            nodejs \
            npm
    volumes:
      # z lets SELinux share this mount (on Fedora, Debians have AppArmor which isn't fussy here)
      - .:/app:z
      # a more robust place for uploads/ perhaps?
      # if you want to serve this without the /error/ directory
      #  see https://github.com/sveltejs/kit/discussions/10162
      - /media/s/www:/app/static/error:ro
      # Prevent the container's node_modules from being overwritten by the host
      #  this means any `npm i ...` you make in another environ (eg the host)
      #   will need pushing to the container via package.json, the above RUN npm ci
        #  as part of a $ docker compose up --build
      # - /app/node_modules
      - /app/.svelte-kit
    ports:
      - "172.17.0.1:9090:3000"
    command: npm run dev -- --port 3000 --host 0.0.0.0
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "http://127.0.0.1:9090"]
    #   interval: 2s
    #   timeout: 5s
    #   retries: 16
    #   start_period: 30s
    restart: always
